language: c
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config build-essential
  - mkdir bin
script:
  - make debug
  - make test
  - ./bin/quantica_test
