language: c
notifications:
  email:
    on_success: always
    on_failure: always
compiler:
  - clang
  - gcc
before_script:
  - mkdir bin
script:
  - make debug
  - make test
  - ./bin/quantica_test
